"""Report renderer — Markdown + JSON schema output (WBS 7.10; v2 T-011).

schema_version 2 adds react_trace (tool call audit), react_verdict,
and an insufficient_evidence report branch (ADR-024, T-010).
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

_SCHEMA_VERSION = 2


def render_md(state: dict[str, Any]) -> str:
    """Render a Markdown diagnosis report from agent state."""
    react_verdict = state.get("react_verdict", "diagnosed")

    # ── Insufficient evidence branch (ADR-024 / T-010) ────────────────────────
    if react_verdict != "diagnosed":
        return _render_insufficient_md(state)

    fault_kind = state.get("fault_kind", "unknown")
    fault_summary = state.get("fault_summary", "")
    olk_tag = state.get("olk_version_tag", "unknown")
    hostname = state.get("hostname") or "unknown"
    final_analysis = state.get("final_analysis", "") or state.get("react_final_answer", "")
    # Backward-compat: if state was built by old bind_claims (or by test
    # fixtures using `claims` only), derive the split from the `verified`
    # flag so old callers still render correctly.
    verified_claims = state.get("verified_claims")
    speculative_claims = state.get("speculative_claims")
    if verified_claims is None or speculative_claims is None:
        legacy = state.get("claims", []) or []
        verified_claims = [c for c in legacy if c.get("verified")]
        speculative_claims = [c for c in legacy if not c.get("verified")]
    groundedness = state.get("groundedness")
    if groundedness is None:
        if not verified_claims and not speculative_claims:
            groundedness = "speculative"
        elif verified_claims and len(verified_claims) >= len(speculative_claims):
            groundedness = "grounded"
        else:
            groundedness = "speculative"
    evidence = state.get("evidence", [])
    tool_trace = state.get("react_tool_trace", [])
    iterations = state.get("react_iterations", 0)
    tokens_used = state.get("react_tokens_used", 0)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # v2.1 P0-1: surface groundedness in the report header so users see at a
    # glance whether the diagnosis is evidence-backed or LLM speculation.
    groundedness_banner = {
        "grounded":    "**Diagnosis quality:** ✓ GROUNDED — supporting claims trace to retrieved evidence.",
        "speculative": "**Diagnosis quality:** ⚠ SPECULATIVE — claims could not be fully matched to retrieved evidence; treat the conclusion as agent speculation, not verified fact.",
        "n/a":         "**Diagnosis quality:** N/A",
    }.get(groundedness, "")

    lines: list[str] = [
        "# Linux Kernel Fault Diagnosis Report",
        "",
        f"**Generated:** {timestamp}  ",
        f"**Host:** {hostname}  ",
        f"**Kernel:** {olk_tag}  ",
        f"**Fault type:** `{fault_kind}`  ",
        f"**Investigation:** {iterations} iterations · {tokens_used:,} tokens  ",
        groundedness_banner + "  ",
        "",
        "## Executive Summary",
        "",
        fault_summary or "_No fault summary available._",
        "",
        "## Root Cause Analysis",
        "",
        final_analysis or "_Analysis not available._",
        "",
    ]

    if verified_claims:
        lines += ["## ✓ Verified Claims (grounded in evidence)", ""]
        for c in verified_claims:
            refs = ", ".join(c.get("evidence_refs", []))
            strength = c.get("evidence_strength", 0.0)
            lines.append(
                f"- {c.get('text','')} "
                f"_(refs: {refs}; evidence-overlap: {strength:.2f})_"
            )
        lines.append("")

    if speculative_claims:
        lines += [
            "## ⚠ Agent Speculation (NOT verified against retrieved evidence)",
            "",
            "_These claims were generated by the LLM but could not be matched to "
            "the cited evidence with enough confidence. Treat as hypotheses, "
            "not facts._",
            "",
        ]
        for c in speculative_claims:
            refs = ", ".join(c.get("evidence_refs", []))
            strength = c.get("evidence_strength", 0.0)
            reason = ("no cited evidence resolved to retrieved rows"
                      if not refs or strength == 0.0
                      else f"low overlap {strength:.2f} (threshold 0.20)")
            lines.append(
                f"- {c.get('text','')} _(refs: {refs or 'none'}; {reason})_"
            )
        lines.append("")

    if evidence:
        lines += [
            "## Retrieved Evidence",
            "",
            "| # | Route | Title | Score |",
            "|---|-------|-------|-------|",
        ]
        for i, ev in enumerate(evidence[:10], 1):
            title = ev.get("title", "")[:60]
            lines.append(
                f"| {i} | {ev.get('route','')} | {title} | {ev.get('score',0):.3f} |"
            )
        lines.append("")

    if tool_trace:
        lines += ["## Tool Call Trace", ""]
        for entry in tool_trace:
            status = "✗" if entry.get("error") else "✓"
            lines.append(
                f"- [{status}] step {entry['step']} `{entry['tool']}` args={entry['args']}"
            )
        lines.append("")

    lines += ["---", "_Report generated by Linux-Diag-Agent v2_"]
    return "\n".join(lines)


def _render_insufficient_md(state: dict[str, Any]) -> str:
    """Render an insufficient-evidence report with next-step guidance (T-010)."""
    react_verdict = state.get("react_verdict", "insufficient_evidence")
    final_answer = state.get("react_final_answer", "")
    fault_kind = state.get("fault_kind", "unknown")
    olk_tag = state.get("olk_version_tag", "unknown")
    hostname = state.get("hostname") or "unknown"
    iterations = state.get("react_iterations", 0)
    tokens_used = state.get("react_tokens_used", 0)
    tool_trace = state.get("react_tool_trace", [])
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    verdict_label = {
        "insufficient_evidence": "Insufficient Evidence",
        "max_iter_reached": "Investigation Limit Reached",
        "budget_exhausted": "Token Budget Exhausted",
    }.get(react_verdict, react_verdict)

    lines = [
        "# Linux Kernel Fault Diagnosis — Incomplete",
        "",
        f"**Generated:** {timestamp}  ",
        f"**Host:** {hostname}  ",
        f"**Kernel:** {olk_tag}  ",
        f"**Fault type:** `{fault_kind}`  ",
        f"**Outcome:** {verdict_label} ({iterations} iterations · {tokens_used:,} tokens)  ",
        "",
        "## Diagnosis Status",
        "",
        f"The investigation could not reach a definitive conclusion: **{verdict_label}**.",
        "",
    ]

    if final_answer:
        lines += [
            "## Additional Information Required",
            "",
            final_answer,
            "",
        ]
    else:
        lines += [
            "## Suggested Next Steps",
            "",
            "- Provide the full dmesg output (including timestamps) from the affected system.",
            "- If a kernel panic occurred, provide the vmcore file for crash forensics.",
            "- Include the exact kernel version (`uname -r`) and hardware model.",
            "- Run `sosreport` on the affected system and share the archive.",
            "",
        ]

    if tool_trace:
        lines += ["## Tools Called", ""]
        for entry in tool_trace:
            status = "✗" if entry.get("error") else "✓"
            lines.append(
                f"- [{status}] step {entry['step']} `{entry['tool']}`"
            )
        lines.append("")

    lines += ["---", "_Report generated by Linux-Diag-Agent v2_"]
    return "\n".join(lines)


def render_json(state: dict[str, Any]) -> dict[str, Any]:
    """Return a structured JSON report dict (schema_version 2)."""
    react_verdict = state.get("react_verdict", "diagnosed")
    tool_trace = state.get("react_tool_trace", [])

    base: dict[str, Any] = {
        "schema_version": _SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "system": {
            "hostname": state.get("hostname"),
            "olk_version_tag": state.get("olk_version_tag"),
            "kernel_version": state.get("kernel_version"),
        },
        "fault": {
            "kind": state.get("fault_kind"),
            "summary": state.get("fault_summary"),
            "diagnostic_route": state.get("diagnostic_route"),
        },
        "react": {
            "verdict": react_verdict,
            "iterations": state.get("react_iterations", 0),
            "tokens_used": state.get("react_tokens_used", 0),
            "tool_calls": [
                {
                    "step": t.get("step"),
                    "tool": t.get("tool"),
                    "args": t.get("args"),
                    "error": t.get("error", False),
                }
                for t in tool_trace
            ],
        },
    }

    if react_verdict == "diagnosed":
        base["analysis"] = {
            "final": state.get("final_analysis") or state.get("react_final_answer"),
        }
        base["claims"] = state.get("claims", [])
        base["verified_claims"] = state.get("verified_claims", [])
        base["speculative_claims"] = state.get("speculative_claims", [])
        base["groundedness"] = state.get("groundedness", "speculative")
        base["evidence_count"] = len(state.get("evidence", []))
        base["top_evidence"] = [
            {
                "route": e.get("route"),
                "title": e.get("title"),
                "score": e.get("score"),
                "commit_hash": e.get("commit_hash"),
                "bug_id": e.get("bug_id"),
                "cve_id": e.get("cve_id"),
            }
            for e in state.get("evidence", [])[:10]
        ]
    else:
        base["insufficient_evidence"] = {
            "reason": react_verdict,
            "agent_message": state.get("react_final_answer", ""),
        }

    return base
