"""Report renderer — Markdown + JSON schema output (WBS 7.10; v2 T-011).

schema_version 2 adds react_trace (tool call audit), react_verdict,
and an insufficient_evidence report branch (ADR-024, T-010).

2026-06-01: bilingual Markdown report (lang='en' / lang='zh'). UI-language
flows from web/server.py through web/streaming_pipeline.py.
JSON output stays English regardless of lang for API stability.

2026-06-01 (SRE redesign): the report is now SRE-incident-style:
  - One metadata strip (fault + host + kernel + quality + cost)
  - The LLM's <final_answer> body becomes the top-level content directly
    (no '## Root Cause Analysis' wrapper that duplicated the LLM's own
     '## Root Cause' / '## Fix Recommendation' / '## Confidence' headers)
  - '## Evidence Check' replaces the noisy Verified/Speculative split
    with a per-claim verdict + reason + cited evidence (5 max)
  - Top-5 retrieved evidence rows only (was 10)
  - Full tool-call trace folded behind a <details> element
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

_SCHEMA_VERSION = 2
_OVERLAP_THRESHOLD = 0.20


_STR: dict[str, dict[str, Any]] = {
    "en": {
        # ── Header / metadata strip ──
        "title": "Kernel Fault Diagnosis",
        "title_incomplete": "Kernel Fault Diagnosis — Incomplete",
        "k_fault": "Fault",
        "k_host": "Host",
        "k_kernel": "Kernel",
        "k_quality": "Quality",
        "k_at": "at",
        "k_cost": "Cost",
        "u_iter": "iter",
        "u_tokens": "tok",
        "quality_grounded": "✓ grounded (claims trace to retrieved evidence)",
        "quality_speculative": "⚠ speculative (claims partly unverified)",
        "quality_na": "n/a",
        # ── Body ──
        "h_evidence_check": "## Evidence Check",
        "k_pool_size": "evidence pool",
        "k_threshold": "verification threshold",
        "k_verified": "verified",
        "k_speculative": "speculative",
        "label_verified_mark": "✓ verified",
        "label_speculative_mark": "✗ speculative",
        "label_cited_in": "cited evidence",
        "label_reason": "reason",
        "reason_no_evidence": "LLM cited no evidence",
        "reason_low_overlap": "low semantic overlap {strength:.2f} (threshold {thr:.2f})",
        "reason_ok": "evidence_strength {strength:.2f} ≥ {thr:.2f}",
        "reason_thin": "evidence too thin to confirm",
        "h_top_evidence": "## Top Evidence (top 5 of {n})",
        "tbl_evidence_header": "| # | Route | Title | Score |",
        "tbl_evidence_sep":    "|---|-------|-------|-------|",
        "details_trace": "Tool call trace ({n} calls)",
        "h_status": "## Status",
        "msg_status": (
            "The investigation could not reach a definitive conclusion: "
            "**{verdict}**."
        ),
        "h_additional_info": "## Agent Message",
        "h_suggested": "## What to Provide Next",
        "next_steps": [
            "- Full dmesg output (with timestamps) from the affected system",
            "- If a kernel panic occurred: the vmcore file",
            "- Exact kernel version (`uname -r`) and hardware model",
            "- A `sosreport` archive from the affected system",
        ],
        "footer": "_Generated by Linux-Diag-Agent v2 · full structured data in report_json_",
        "step_word": "step",
        "unknown_value": "unknown",
        "verdicts": {
            "insufficient_evidence": "Insufficient Evidence",
            "max_iter_reached":      "Investigation Limit Reached",
            "budget_exhausted":      "Token Budget Exhausted",
        },
    },
    "zh": {
        # ── 头部元数据条 ──
        "title": "故障诊断报告",
        "title_incomplete": "故障诊断 — 未完成",
        "k_fault": "故障",
        "k_host": "主机",
        "k_kernel": "内核",
        "k_quality": "质量",
        "k_at": "于",
        "k_cost": "成本",
        "u_iter": "轮",
        "u_tokens": "tokens",
        "quality_grounded": "✓ 已扎根（关键声明可追溯到检索证据）",
        "quality_speculative": "⚠ 推测（部分声明未与证据匹配）",
        "quality_na": "n/a",
        # ── 正文 ──
        "h_evidence_check": "## 证据核验",
        "k_pool_size": "候选证据池",
        "k_threshold": "验证阈值",
        "k_verified": "已验证",
        "k_speculative": "推测",
        "label_verified_mark": "✓ 已验证",
        "label_speculative_mark": "✗ 推测",
        "label_cited_in": "引用证据",
        "label_reason": "判定原因",
        "reason_no_evidence": "LLM 未引用任何证据",
        "reason_low_overlap": "语义重叠度 {strength:.2f} 偏低（阈值 {thr:.2f}）",
        "reason_ok": "evidence_strength {strength:.2f} ≥ {thr:.2f}",
        "reason_thin": "证据不足以确证",
        "h_top_evidence": "## 主要证据（共 {n} 条，列前 5 条）",
        "tbl_evidence_header": "| # | 路由 | 标题 | 得分 |",
        "tbl_evidence_sep":    "|---|------|------|------|",
        "details_trace": "完整工具调用 trace（共 {n} 次）",
        "h_status": "## 状态",
        "msg_status": "调研未能得出确定结论：**{verdict}**。",
        "h_additional_info": "## Agent 留言",
        "h_suggested": "## 需要你补充的信息",
        "next_steps": [
            "- 受影响系统完整的 dmesg（含时间戳）",
            "- 如发生内核 panic：vmcore 文件",
            "- 精确的内核版本（`uname -r`）和硬件型号",
            "- 受影响系统的 `sosreport` 归档",
        ],
        "footer": "_由 Linux-Diag-Agent v2 生成 · 完整结构化数据见 report_json_",
        "step_word": "步骤",
        "unknown_value": "未知",
        "verdicts": {
            "insufficient_evidence": "证据不足",
            "max_iter_reached":      "达到调研上限",
            "budget_exhausted":      "Token 预算耗尽",
        },
    },
}


def _S(lang: str) -> dict[str, Any]:
    return _STR["zh"] if (lang or "en").lower() == "zh" else _STR["en"]


def _strip_final_answer_tag(blob: str) -> str:
    """Strip enclosing <final_answer>...</final_answer> tags so the LLM's
    Markdown sections become the report's top-level content.

    Keeps the body verbatim — only the XML wrapper is removed.
    """
    if not blob:
        return ""
    s = blob.strip()
    # Case-insensitive strip of the open/close tags
    lower = s.lower()
    if lower.startswith("<final_answer>"):
        s = s[len("<final_answer>"):].lstrip()
    if lower.endswith("</final_answer>"):
        s = s[:-len("</final_answer>")].rstrip()
    return s


def _metadata_strip(state: dict, S: dict, *, incomplete: bool) -> list[str]:
    """One-line metadata strip at the top of the report (SRE-style)."""
    unknown = S["unknown_value"]
    fault_kind = state.get("fault_kind") or unknown
    olk_tag = state.get("olk_version_tag") or unknown
    hostname = state.get("hostname") or unknown
    iterations = state.get("react_iterations", 0)
    tokens_used = state.get("react_tokens_used", 0)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    quality = _quality_label(state, S, incomplete=incomplete)

    return [
        f"**{S['k_fault']}** `{fault_kind}` · "
        f"**{S['k_host']}** {hostname} · "
        f"**{S['k_kernel']}** {olk_tag}  ",
        f"**{S['k_quality']}** {quality} · "
        f"**{S['k_cost']}** {iterations} {S['u_iter']} / "
        f"{tokens_used:,} {S['u_tokens']} · "
        f"{S['k_at']} {timestamp}  ",
    ]


def _quality_label(state: dict, S: dict, *, incomplete: bool) -> str:
    if incomplete:
        return S["verdicts"].get(state.get("react_verdict", ""), S["quality_na"])
    g = state.get("groundedness")
    if g == "grounded":
        return S["quality_grounded"]
    if g == "speculative":
        return S["quality_speculative"]
    return S["quality_na"]


def _claim_reason(c: dict, S: dict) -> str:
    """Compute a human reason string for why this claim was verified or not."""
    refs = c.get("evidence_refs") or []
    strength = float(c.get("evidence_strength") or 0.0)
    verified = bool(c.get("verified"))
    if verified:
        return S["reason_ok"].format(strength=strength, thr=_OVERLAP_THRESHOLD)
    if not refs:
        return S["reason_no_evidence"]
    if strength > 0 and strength < _OVERLAP_THRESHOLD:
        return S["reason_low_overlap"].format(strength=strength, thr=_OVERLAP_THRESHOLD)
    return S["reason_thin"]


def render_md(state: dict[str, Any], lang: str = "en") -> str:
    """Render a SRE-style Markdown diagnosis report.

    Layout (ZH labels in parens):
      # Kernel Fault Diagnosis  (故障诊断报告)
      <metadata strip>                — fault / host / kernel / quality / cost
      [LLM final_answer body verbatim — its own ## Root Cause / 根本原因, etc.]
      ## Evidence Check               — per-claim verdict + reason + cited rows
      ## Top Evidence (top 5 of N)
      <details>Tool call trace</details>
      ── footer

    ``lang`` ∈ {'en', 'zh'} — picks section headers and banner phrases.
    Data values (commit hashes, function names, user-supplied text,
    LLM output) are NEVER translated by this renderer; the LLM upstream
    already speaks the requested language thanks to kernel.zh.md /
    kernel.md selection in agent/react/prompts/__init__.py.
    """
    react_verdict = state.get("react_verdict", "diagnosed")
    if react_verdict != "diagnosed":
        return _render_insufficient_md(state, lang=lang)

    S = _S(lang)
    final_blob = (state.get("final_analysis") or
                   state.get("react_final_answer") or "")
    final_blob = _strip_final_answer_tag(final_blob)
    evidence = state.get("evidence", []) or []
    tool_trace = state.get("react_tool_trace", []) or []
    claims = state.get("claims") or []

    # Header
    lines: list[str] = [f"# {S['title']}", ""]
    lines += _metadata_strip(state, S, incomplete=False)
    lines.append("")

    # LLM analysis body — no wrapper. Its own ## headers are now top-level.
    # If the body is empty (very rare for diagnosed verdict), fall through
    # to Evidence Check / Top Evidence anyway so the user sees the data.
    if final_blob:
        lines += ["---", "", final_blob, ""]

    # Evidence Check (consolidates the old Verified + Speculative sections).
    # Show top 5 claims max — SRE doesn't want a wall of every claim.
    if claims:
        lines += ["---", "", S["h_evidence_check"], ""]
        verified_n = sum(1 for c in claims if c.get("verified"))
        speculative_n = len(claims) - verified_n
        lines += [
            f"- **{S['k_verified']}**: {verified_n}",
            f"- **{S['k_speculative']}**: {speculative_n}",
            f"- **{S['k_pool_size']}**: {len(evidence)}",
            f"- **{S['k_threshold']}**: ≥ {_OVERLAP_THRESHOLD:.2f}",
            "",
        ]
        evidence_index = _index_evidence(evidence)
        for c in claims[:5]:
            mark = (S["label_verified_mark"] if c.get("verified")
                    else S["label_speculative_mark"])
            text = (c.get("text") or "")[:240]
            strength = float(c.get("evidence_strength") or 0.0)
            reason = _claim_reason(c, S)
            lines.append(f"- {mark} {text}")
            lines.append(f"  - {S['label_reason']}: {reason} · "
                         f"`evidence_strength={strength:.2f}`")
            cited_summaries = _cited_summaries(c.get("evidence_refs") or [],
                                                evidence_index)
            if cited_summaries:
                lines.append(f"  - {S['label_cited_in']}:")
                for s in cited_summaries:
                    lines.append(f"    - {s}")
        lines.append("")

    # Top evidence (5 rows max) — SRE doesn't need 10
    if evidence:
        lines += ["---", "",
                  S["h_top_evidence"].format(n=len(evidence)),
                  "",
                  S["tbl_evidence_header"], S["tbl_evidence_sep"]]
        for i, ev in enumerate(evidence[:5], 1):
            title = (ev.get("title") or "")[:60]
            lines.append(
                f"| {i} | {ev.get('route','')} | {title} | "
                f"{float(ev.get('score', 0) or 0):.3f} |"
            )
        lines.append("")

    # Tool call trace — folded under <details> (Markdown native support)
    if tool_trace:
        lines += [
            "<details>",
            f"<summary>{S['details_trace'].format(n=len(tool_trace))}</summary>",
            "",
        ]
        for entry in tool_trace:
            status = "✗" if entry.get("error") else "✓"
            lines.append(
                f"- [{status}] {S['step_word']} {entry['step']} "
                f"`{entry['tool']}` args={entry.get('args','')}"
            )
        lines += ["", "</details>", ""]

    lines += ["---", S["footer"]]
    return "\n".join(lines)


def _index_evidence(evidence: list[dict]) -> dict[str, dict]:
    idx: dict[str, dict] = {}
    for ev in evidence:
        for k in ("commit_hash", "message_id", "cve_id"):
            v = ev.get(k)
            if v:
                idx[str(v)] = ev
        if ev.get("bug_id"):
            idx[str(ev["bug_id"])] = ev
    return idx


def _cited_summaries(refs: list, ev_index: dict[str, dict]) -> list[str]:
    """Resolve each ref to a one-line summary 'route | id | title'."""
    out: list[str] = []
    for r in refs:
        raw = r[5:] if isinstance(r, str) and r.startswith("AUTO:") else r
        ev = ev_index.get(str(raw))
        if not ev:
            out.append(f"~~{r}~~ _(not in retrieved pool)_")
            continue
        route = ev.get("route") or ""
        hash_short = (ev.get("commit_hash") or "")[:12]
        ident = f"`{hash_short}`" if hash_short else ""
        title = (ev.get("title") or "")[:80]
        auto = " _(auto-attached)_" if isinstance(r, str) and r.startswith("AUTO:") else ""
        out.append(f"[{route}] {ident} {title}{auto}".strip())
    return out


def _render_insufficient_md(state: dict[str, Any], lang: str = "en") -> str:
    """Render an insufficient-evidence report with next-step guidance."""
    S = _S(lang)
    react_verdict = state.get("react_verdict", "insufficient_evidence")
    final_answer = state.get("react_final_answer", "") or ""
    tool_trace = state.get("react_tool_trace", []) or []
    verdict_label = S["verdicts"].get(react_verdict, react_verdict)

    lines = [f"# {S['title_incomplete']}", ""]
    lines += _metadata_strip(state, S, incomplete=True)
    lines += [
        "",
        S["h_status"],
        "",
        S["msg_status"].format(verdict=verdict_label),
        "",
    ]

    final_answer = _strip_final_answer_tag(final_answer)
    if final_answer:
        lines += [S["h_additional_info"], "", final_answer, ""]
    else:
        lines += [S["h_suggested"], "", *S["next_steps"], ""]

    if tool_trace:
        lines += [
            "<details>",
            f"<summary>{S['details_trace'].format(n=len(tool_trace))}</summary>",
            "",
        ]
        for entry in tool_trace:
            status = "✗" if entry.get("error") else "✓"
            lines.append(
                f"- [{status}] {S['step_word']} {entry['step']} "
                f"`{entry['tool']}`"
            )
        lines += ["", "</details>", ""]

    lines += ["---", S["footer"]]
    return "\n".join(lines)


def render_json(state: dict[str, Any]) -> dict[str, Any]:
    """Return a structured JSON report dict (schema_version 2).

    JSON output is intentionally NOT translated — keys and label values
    are stable English identifiers for API consumers. UI / CLI rendering
    of these values can localize at presentation time.
    """
    react_verdict = state.get("react_verdict", "diagnosed")
    tool_trace = state.get("react_tool_trace", [])

    base: dict[str, Any] = {
        "schema_version": _SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "system": {
            "hostname": state.get("hostname"),
            "olk_version_tag": state.get("olk_version_tag"),
            "kernel_version": state.get("kernel_version"),
        },
        "fault": {
            "kind": state.get("fault_kind"),
            "summary": state.get("fault_summary"),
            "diagnostic_route": state.get("diagnostic_route"),
        },
        "react": {
            "verdict": react_verdict,
            "iterations": state.get("react_iterations", 0),
            "tokens_used": state.get("react_tokens_used", 0),
            "tool_calls": [
                {
                    "step": t.get("step"),
                    "tool": t.get("tool"),
                    "args": t.get("args"),
                    "error": t.get("error", False),
                }
                for t in tool_trace
            ],
        },
    }

    if react_verdict == "diagnosed":
        base["analysis"] = {
            "final": state.get("final_analysis") or state.get("react_final_answer"),
        }
        base["claims"] = state.get("claims", [])
        base["verified_claims"] = state.get("verified_claims", [])
        base["speculative_claims"] = state.get("speculative_claims", [])
        base["groundedness"] = state.get("groundedness", "speculative")
        base["evidence_count"] = len(state.get("evidence", []))
        base["top_evidence"] = [
            {
                "route": e.get("route"),
                "title": e.get("title"),
                "score": e.get("score"),
                "commit_hash": e.get("commit_hash"),
                "bug_id": e.get("bug_id"),
                "cve_id": e.get("cve_id"),
            }
            for e in state.get("evidence", [])[:10]
        ]
    else:
        base["insufficient_evidence"] = {
            "reason": react_verdict,
            "agent_message": state.get("react_final_answer", ""),
        }

    return base
